name: games_2d_CI

on:
    push:
        branches:
            - master

jobs:
    games-2d-CI:
        runs-on: ubuntu-latest
        steps:
            - name: Make git clone
              uses: actions/checkout@v3

            - name: Setup fvm
              uses: kuhnroyal/flutter-fvm-config-action@v1
              with:
                  path: '.fvm/fvm_config.json'

            - name: Clone flutter version
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: ${{ env.FLUTTER_VERSION }}
                  channel: ${{ env.FLUTTER_CHANNEL }}

            - name: Update dependencies of root project
              run: flutter pub get

            - name: Update dependencies of inner projects (Melos)
              run: dart run melos bs

            - name: Run all static analysis checks of inner projects (Melos)
              run: dart run melos run lint:all

            - name: Build and deploy bill_runner project (GitHub Pages)
              uses: bluefireteam/flutter-gh-pages@v8
              with:
                  workingDir: ./games/bill_runner
                  baseHref: /games_2d/
                  webRenderer: canvaskit
                  targetBranch: bill-runner-page
