name: games_2d_CI

on:
    push:
        branches:
            - master

jobs:
    games-2d-CI:
        runs-on: ubuntu-latest
        steps:
            - name: Make git clone
              uses: actions/checkout@v2

            - name: Setup fvm
              uses: kuhnroyal/flutter-fvm-config-action@v1
              with:
                  path: '.fvm/fvm_config.json'

            - name: Clone flutter version
              uses: subosito/flutter-action@v1
              with:
                  flutter-version: ${{ env.FLUTTER_VERSION }}
                  channel: ${{ env.FLUTTER_CHANNEL }}

            - name: Update dependencies of root project
              run: flutter pub get

            - name: Update dependencies of inner projects (Melos)
              run: dart run melos bs

            - name: Run all static analysis checks of inner projects (Melos)
              run: dart run melos run lint:all

#            - name: run tests
#              run: flutter test --concurrency=1 --coverage --test-randomize-ordering-seed random
#
#            - name: Upload coverage reports to Codecov
#              uses: codecov/codecov-action@v3
#              env:
#                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
